Converted the policies to gatekeeper naming/structure

diff --git a/.github/workflows/conftest.yaml b/.github/workflows/conftest.yaml
--- a/.github/workflows/conftest.yaml
+++ b/.github/workflows/conftest.yaml
@@ -9,8 +9,25 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
+      - name: Generate konstraint docs
+        uses: garethahealy/github-actions/confbatstest@conftest-raw
+        with:
+          raw: konstraint doc -o POLICIES.md
+
+      - name: Check if there are changes to POLICIES.md
+        id: changes
+        uses: UnicornGlobal/has-changes-action@master
+        with:
+          pathspec: POLICIES.md
+
+      - name: Fail if POLICIES.md changes found
+        if: steps.changes.outputs.changed == 1
+        run: |
+          echo "Uncommited changes to POLICIES.md exist. Failing."
+          exit 1
+
       - name: Conftest
         uses: redhat-cop/github-actions/confbatstest@master
         with:
-          tests: _test/conftest.sh
+          tests: _test/conftest-unittests.sh
           policies: '[{"name": "deprek8ion", "url":"github.com/swade1987/deprek8ion.git//policies"}]'
